version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: tonmoy404
      MYSQL_DATABASE: crud_db
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  nestjs:
    image: node:18
    container_name: nestjs-container
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: ['yarn', 'start:dev']
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: tonmoy404
      DB_NAME: crud_db

    env_file:
      - .env

volumes:
  mysql-data:
